default: true
MD013: false  # Line length
MD033: false  # Inline HTML
MD041: false  # First line in file should be a top level header
MD024: false  # Multiple headers with the same content
MD025: false  # Multiple top level headers
MD002: false  # First header should be a top level header